# need to use sudo-enabled containers for additional RAM
sudo: required
language: java
jdk: oraclejdk8
python:
  - "3.6"
cache:
  directories:
    - "backend/node_modules"
install:
  - cd backend
  - npm install
  - cd ..
before_script:
  - export WYVERN_HOME="$(pwd)"
  - export _JAVA_OPTIONS="-Xmx6144m -Xms512m"
script:
  - cd tools
  - ant test
  - cd ../backend
  - ./bootstrap.sh travis
  - ./test.sh
notifications:
  email:
    recipients:
      - jonathan.aldrich@cs.cmu.edu
